name: Deploy

on:
  push:
    branches:
      - main

jobs:
  # Run integration tests before deploying
  test:
    name: Install and test
    runs-on: ubuntu-latest
    strategy:
      matrix: #You can specify an array of versions that the tests will run against.
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Install dependencies
      - run: npm install
      # Run tests
      - run: npm run test
        env:
          CI: true

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'innovation-api-app' #Must be unique in Heroku
          heroku_email: 'laoussamaofficial@gmail.com'
          usedocker: true
        env:
          HD_NODE_ENV: 'production'
          HD_MONGO_URI: ${{ secrets.MONGO_URI }}
          HD_PORT: 8080
